### ISSUE TITLE
TypeError: Path must be a string. Received true

### ISSUE THREAD

**Issue by TangMonk** [sequelize/sequelize-auto#112]
```
$  sequelize-auto -h localhost -d create_trip -u root -x root -p 3306 -dialect mysql -o './server/models/'

path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received true
    at assertPath (path.js:8:11)
    at Object.posix.resolve (path.js:426:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/sequelize-auto/bin/sequelize-auto:42:29)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:990:3
```

**Comment by durango** [comment]
Please update sequelize-auto and try again, if you're still running into problems please reopen the issue.

**Comment by joggerjoel** [comment]
I'm getting a similar error with ubuntu 18.04

npm install -g sequelize-auto
npm install -g sequelize
npm install -g mysql

`sequelize-auto -o "./models" -h localhost -d dev_v400 -u root -x123456 -dialect mysql`

path.js:28
   throw new TypeError('Path must be a string. Received ' + inspect(path));
   ^

TypeError: Path must be a string. Received [ true, true ]
   at assertPath (path.js:28:11)
(/usr/local/lib/node_modules/sequelize-auto/bin/sequelize-auto:53:29)
   at bootstrap_node.js:609:3
