### ISSUE TITLE
MSSQL support

### ISSUE THREAD

**Issue by Bondifrench** [sequelize/sequelize-auto#12]
Sequelize now supports Microsoft SQL Server http://sequelize.readthedocs.org/en/latest/docs/getting-started/, does sequelize-auto support MS SQL?
is it just a question of installing tedious and putting it in package.json?

**Comment by Groxot** [comment]
+1

**Comment by Sk1Zy** [comment]
+1

**Comment by marcsmith** [comment]
+1

**Comment by elias-ribeiro** [comment]
+1

**Comment by adonomay** [comment]
+1

**Comment by jjduarte** [comment]
+1

**Comment by slang800** [comment]
:+1:

**Comment by slang800** [comment]
And @Bondifrench: no... installing tedious won't enable support... this was built upon 1.7.0-alpha2 (rather than 3.3.1, which is the current stable release), so it probably doesn't even support the mssql adaptor.

**Comment by RaveNoX** [comment]
MS SQL support merged to master by https://github.com/sequelize/sequelize-auto/pull/18
Please fetch lastest master and try to use it.

**Comment by brettveenstra** [comment]
Seems like there's a dependency problem... as a hack you could clone the latest repo down locally and then install globally via npm

e.g.  `npm install -g ./path-to-repo' it should allow the 'mssql' dialect

**Comment by riemannzeta** [comment]
installing from latest repo seems to have gotten closer to working... but sequelize-auto is now throwing the following error:

Unhandled rejection TypeError: undefined is not a function
    at /usr/local/lib/node_modules/sequelize-auto/lib/index.js:100:59
    at Array.forEach (native)
    at /usr/local/lib/node_modules/sequelize-auto/lib/index.js:77:25
    at Array.forEach (native)
    at /usr/local/lib/node_modules/sequelize-auto/lib/index.js:63:18
    at /usr/local/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:187:20
    at /usr/local/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:239:13
    at _arrayEach (/usr/local/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:91:13)
    at _each (/usr/local/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:82:13)
    at Object.async.forEachOf.async.eachOf (/usr/local/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:238:9)
    at Object.async.forEach.async.each (/usr/local/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:215:22)
    at /usr/local/lib/node_modules/sequelize-auto/lib/index.js:51:15
    at /usr/local/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:52:16
    at done (/usr/local/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:248:21)
    at /usr/local/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:44:16
    at /usr/local/lib/node_modules/sequelize-auto/lib/index.js:47:13


interestingly, i get a slightly different error running on the server side (the cut-and-paste from above is the error i get running off my local instances)

Unhandled rejection TypeError: Object true has no method 'toLowerCase'
    at /home/y/lib/node_modules/sequelize-auto/lib/index.js:100:59
    at Array.forEach (native)
    at /home/y/lib/node_modules/sequelize-auto/lib/index.js:77:25
    at Array.forEach (native)
    at /home/y/lib/node_modules/sequelize-auto/lib/index.js:63:18
    at /home/y/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:187:20
    at /home/y/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:239:13
    at _arrayEach (/home/y/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:91:13)
    at _each (/home/y/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:82:13)
    at Object.async.forEachOf.async.eachOf (/home/y/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:238:9)
    at Object.async.forEach.async.each (/home/y/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:215:22)
    at /home/y/lib/node_modules/sequelize-auto/lib/index.js:51:15
    at /home/y/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:52:16
    at done (/home/y/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:248:21)
    at /home/y/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:44:16
    at /home/y/lib/node_modules/sequelize-auto/lib/index.js:47:13
From previous event:
    at Promise.then (/home/y/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/promise.js:21:17)
    at AutoSequelize.run (/home/y/lib/node_modules/sequelize-auto/lib/index.js:33:6)
    at Object.<anonymous> (/home/y/lib/node_modules/sequelize-auto/bin/sequelize-auto:39:6)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:123:16)
    at node.js:945:3

**Comment by durango** [comment]
@riemannzeta could u update sequelize-auto and give it another go please?

**Comment by durango** [comment]
Based off of another issue, it seems like this is really OK/fixed. https://github.com/sequelize/sequelize-auto/issues/20

**Comment by DaveRicho** [comment]
Hi Guys, sorry to be a pain, but after trying the ideas in #20 and this issue, I'm still having the mssql dialect issue. It is probably something obvious and I am just stupid (apologies in advance as I'm fairly new to node).

Thanks for your time (this looks like such as great tool - I really hope I can get it working!!).

Here is the error message:

Error: The dialect 'mssql' is not supported. Supported dialects: mariadb, mssql, mysql, postgres, and sqlite.
    at new Sequelize (C:\Users\someguy\AppData\Roaming\npm\node_modules\sequelize-auto\node_modules\sequelize\lib\sequelize.js:231:13)
    at new AutoSequelize (C:\Users\someguy\AppData\Roaming\npm\node_modules\sequelize-auto\lib\index.js:10:20)
    at Object.<anonymous> (C:\Users\someguy\AppData\Roaming\npm\node_modules\sequelize-auto\bin\sequelize-auto:59:75)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
