### ISSUE TITLE
Cannot call method 'createConnection' of undefined

### ISSUE THREAD

**Issue by Misterhex** [sequelize/sequelize-auto#13]
When running against a wordpress mysql db, its throwing an error back at me. 

```
var connection = mysql.createConnection(connectionConfig);
                           ^
TypeError: Cannot call method 'createConnection' of undefined
    at module.exports.connect (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/dialects/mysql/connector-manager.js:306:28)
    at Object.pool.Pooling.Pool.create (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/dialects/mysql/connector-manager.js:131:19)
    at createResource (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/node_modules/generic-pool/lib/generic-pool.js:258:13)
    at dispense (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/node_modules/generic-pool/lib/generic-pool.js:250:9)
    at Object.me.acquire (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/node_modules/generic-pool/lib/generic-pool.js:316:5)
    at null.fct (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/dialects/mysql/connector-manager.js:241:19)
    at null.<anonymous> (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/emitters/custom-event-emitter.js:24:18)
    at processImmediate [as _immediateCallback] (timers.js:354:15
```

**Comment by Sk1Zy** [comment]
So what was the solution? Having the exact same problem.

**Comment by ObjectiveTruth** [comment]
@Misterhex I'm having this same issue that you did here, not sure what I'm doing wrong? is there a dependency I'm missing?

```
You need to install mysql package manually

/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/dialects/mysql/connector-manager.js:306
    var connection = mysql.createConnection(connectionConfig);
                           ^
TypeError: Cannot call method 'createConnection' of undefined
    at module.exports.connect (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/dialects/mysql/connector-manager.js:306:28)
    at Object.pool.Pooling.Pool.create (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/dialects/mysql/connector-manager.js:131:19)
    at createResource (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/node_modules/generic-pool/lib/generic-pool.js:258:13)
    at dispense (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/node_modules/generic-pool/lib/generic-pool.js:250:9)
    at Object.me.acquire (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/node_modules/generic-pool/lib/generic-pool.js:316:5)
    at null.fct (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/dialects/mysql/connector-manager.js:241:19)
    at null.<anonymous> (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/emitters/custom-event-emitter.js:24:18)
```

**Comment by capaj** [comment]
@ObjectiveTruth yes, I solved this by installing mysql:
`npm i mysql -g`
