### ISSUE TITLE
Not able to pass SSL cert in command line

### ISSUE THREAD

**Issue by shahbits22** [sequelize/sequelize-auto#181]
Hi, 

I need help with passing SSL cert in sequelize-auto command. I am using the below command

`sequelize-auto -o "./models" -d dscs -a ./helpers/options.json -h <hostname> -u <username> -p <port> -x <password> -e mysql -c config.json`

config.json
 ```
"dialectOptions": {
        "ssl": {
            "ca"   : "./ssl/abc.ca.pem",
            "key"  : "./ssl/abc.key",
            "cert" : "./ssl/abc.pem"
        }
    }
```
I get the below error:
```
/usr/local/lib/node_modules/mysql/lib/protocol/Parser.js:80
        throw err; // Rethrow non-MySQL errors
        ^

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Error (native)
    at Object.createSecureContext (_tls_common.js:69:17)
    at Connection._startTLS (/usr/local/lib/node_modules/mysql/lib/Connection.js:288:29)
    at Handshake.<anonymous> (/usr/local/lib/node_modules/mysql/lib/protocol/Protocol.js:174:24)
    at emitNone (events.js:86:13)
    at Handshake.emit (events.js:185:7)
    at Handshake.HandshakeInitializationPacket (/usr/local/lib/node_modules/mysql/lib/protocol/sequences/Handshake.js:58:10)
    at Protocol._parsePacket (/usr/local/lib/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/usr/local/lib/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/usr/local/lib/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)
```

**Comment by sarikaya** [comment]
Is there any progress?

**Comment by qinxiaowen** [comment]
{
    dialectOptions: {
        ssl: {
            rejectUnauthorized: false
        }
    },
    pool: {
        max: 5,
        min: 0,
        acquire: 30000,
        idle: 10000
    }
}
try do it to resolve it , your code lack of '{}',good luck

**Comment by steveschmitt** [comment]
You can try creating the Sequelize instance first, and then passing that to SequelizeAuto, as described in the [README](https://github.com/sequelize/sequelize-auto/blob/master/README.md#programmatic-api)
