### ISSUE TITLE
Please install Tedious Error

### ISSUE THREAD

**Issue by redevill** [sequelize/sequelize-auto#228]
**Environment:**
Node 9.10.1
Sequelize-auto 0.4.29
MSSql Express V12.0.5 SP2
NPM 5.6.0
Sequelize 4.35.0

**Steps to repro:**
npm install -g sequelize-auto
npm install -g mssql
sequelize-auto -o "./Models" -d DatbaseName -h hostIP -u User -x Password -c "./config/config.json" -e mssql -z

Same message after installing tedious
(npm install tedious)

Error: Please install tedious package manually
    at new ConnectionManager (/Users/Eti/.npm-packages/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/dialects/mssql/connection-manager.js:21:13)
    at new MssqlDialect (/Users/Eti/.npm-packages/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/dialects/mssql/index.js:12:28)
    at new Sequelize (/Users/Eti/.npm-packages/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/sequelize.js:233:18)
    at new AutoSequelize (/Users/Eti/.npm-packages/lib/node_modules/sequelize-auto/lib/index.js:19:22)
    at Object.<anonymous> (/Users/Eti/.npm-packages/lib/node_modules/sequelize-auto/bin/sequelize-auto:90:12)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3

**Comment by dimitar-nikovski** [comment]
To be honest, sequelize cannot connect to SQL Server without tedious, regardless of whether sequelize-auto is being used or not, therefore tedious is a dev dependency of sequelize (check [sequelize/package.json](https://github.com/sequelize/sequelize/blob/master/package.json)) rather than a dependency of sequelize-auto. Also, considering that a connection to mssql cannot happen without tedious, it should be a project dependency, rather than a global one, if the project is required to work after changing machines and reinstalling the dependencies.

**Comment by redevill** [comment]
I realize this is a dumb error for someone working in this space, and that sequelize is most likely the first stop, and then this package. (and hence would have no error) But if you come here without context and follow the set up instructions verbatim (including the stipulated prerequisites) to get it to work, and you get an error - then the docs are deficient.  A small change in documentation would save the noobs a headache :) 

PS... BTW not trying to be a pain, just want to participate to try and make a good thing better!

**Comment by bburns** [comment]
I think tedious needs to be in the same place as sequelize-auto - I was able to get it working with

    yarn add sequelize-auto mssql tedious
    node_modules/.bin/sequelize-auto ........

**Comment by steveschmitt** [comment]
I think this is fixed in `sequelize-auto@0.5.0`  
Please try it and close this issue if so.  Thanks!

**Comment by steveschmitt** [comment]
Fixed in `sequelize-auto@0.5.1`.  Now `sequelize-auto` uses the same `sequelize` that you have installed (instead of installing its own).
