### ISSUE TITLE
ER_ACCESS_DENIED_ERROR

### ISSUE THREAD

**Issue by zAndrey95** [sequelize/sequelize-auto#344]
I use sequelize-auto to generate models with mysql. But it does not work. 
Error: ER_ACCESS_DENIED_ERROR 
Who faced this?
I using SUDO command. 

`SequelizeAccessDeniedError: ER_ACCESS_DENIED_ERROR: Access denied for user '7edb113c_aa34_a'@'194.29.63.139' (using password: YES)
    at Handshake.<anonymous> (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:83:20)
    at Handshake.<anonymous> (/usr/local/lib/node_modules/mysql/lib/Connection.js:502:10)
    at Handshake._callback (/usr/local/lib/node_modules/mysql/lib/Connection.js:468:16)
    at Handshake.Sequence.end (/usr/local/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Handshake.ErrorPacket (/usr/local/lib/node_modules/mysql/lib/protocol/sequences/Handshake.js:126:8)
    at Protocol._parsePacket (/usr/local/lib/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/usr/local/lib/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/usr/local/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/usr/local/lib/node_modules/mysql/lib/Connection.js:502:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
  name: 'SequelizeAccessDeniedError',
  message: 'ER_ACCESS_DENIED_ERROR: Access denied for user \'7edb113c_aa34_a\'@\'194.29.63.139\' (using password: YES)',
  parent: 
   { Error: ER_ACCESS_DENIED_ERROR: Access denied for user '7edb113c_aa34_a'@'194.29.63.139' (using password: YES)
    at Handshake.Sequence._packetToError (/usr/local/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/usr/local/lib/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/usr/local/lib/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/usr/local/lib/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/usr/local/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/usr/local/lib/node_modules/mysql/lib/Connection.js:502:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
    --------------------
    at Protocol._enqueue (/usr/local/lib/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/usr/local/lib/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/usr/local/lib/node_modules/mysql/lib/Connection.js:118:18)
    at /usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:75:16
    at Promise._execute (/usr/local/lib/node_modules/sequelize-auto/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/usr/local/lib/node_modules/sequelize-auto/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/usr/local/lib/node_modules/sequelize-auto/node_modules/bluebird/js/release/promise.js:79:10)
    at ConnectionManager.connect (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:55:10)
    at ConnectionManager.<anonymous> (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:247:43)
    at ConnectionManager.tryCatcher (/usr/local/lib/node_modules/sequelize-auto/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/sequelize-auto/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/sequelize-auto/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/sequelize-auto/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/sequelize-auto/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/usr/local/lib/node_modules/sequelize-auto/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/local/lib/node_modules/sequelize-auto/node_modules/bluebird/js/release/async.js:131:9)
     code: 'ER_ACCESS_DENIED_ERROR',
     errno: 1045,
     sqlMessage: 'Access denied for user \'7edb113c_aa34_a\'@\'194.29.63.139\' (using password: YES)',
     sqlState: '28000',
     fatal: true },
  original: 
   { Error: ER_ACCESS_DENIED_ERROR: Access denied for user '7edb113c_aa34_a'@'194.29.63.139' (using password: YES)
    at Handshake.Sequence._packetToError (/usr/local/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/usr/local/lib/node_modules/mysql/lib/protocol/sequences/Handshake.js:124:18)
    at Protocol._parsePacket (/usr/local/lib/node_modules/mysql/lib/protocol/Protocol.js:278:23)
    at Parser.write (/usr/local/lib/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/usr/local/lib/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/mysql/lib/Connection.js:91:28)
    at Socket.<anonymous> (/usr/local/lib/node_modules/mysql/lib/Connection.js:502:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
    --------------------
    at Protocol._enqueue (/usr/local/lib/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/usr/local/lib/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/usr/local/lib/node_modules/mysql/lib/Connection.js:118:18)
    at /usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:75:16
    at Promise._execute (/usr/local/lib/node_modules/sequelize-auto/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (/usr/local/lib/node_modules/sequelize-auto/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/usr/local/lib/node_modules/sequelize-auto/node_modules/bluebird/js/release/promise.js:79:10)
    at ConnectionManager.connect (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:55:10)
    at ConnectionManager.<anonymous> (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:247:43)
    at ConnectionManager.tryCatcher (/usr/local/lib/node_modules/sequelize-auto/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/sequelize-auto/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/sequelize-auto/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/sequelize-auto/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/sequelize-auto/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/usr/local/lib/node_modules/sequelize-auto/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/local/lib/node_modules/sequelize-auto/node_modules/bluebird/js/release/async.js:131:9)
     code: 'ER_ACCESS_DENIED_ERROR',
     errno: 1045,
     sqlMessage: 'Access denied for user \'7edb113c_aa34_a\'@\'194.29.63.139\' (using password: YES)',
     sqlState: '28000',
     fatal: true } }
Done!
`

my connection

`const sequelize = new Sequelize('7edb113c_***_fakturaassist', '7e***_a', '***', {
  host: 'aurora.hssoft.com',
  port : '3306',
  dialect: 'mysql',
  operatorsAliases: false,
  ssl: true,
  dialectOptions: {
    ssl: 'Amazon RDS',
    multipleStatements: true
  },

  pool: {
    max: 5,
    min: 0,
    acquire: 30000,
    idle: 10000
  }
});`

command 

`sequelize-auto -o "./models" -h aurora.hssoft.com -d 7edb113c_***_fakturaassist -u "7edb**_a" -x "***" -p 3306 -d mysql -C
`

**Comment by steveschmitt** [comment]
We just released  `sequelize-auto@0.5.1` which may fix the problem.  Can you please try it and see?

**Comment by steveschmitt** [comment]
I think this was a problem with older `sequelize-auto` because it used an older version of `sequelize`.  Working in current version.
