### ISSUE TITLE
SequelizeAccessDeniedError

### ISSUE THREAD

**Issue by samyulam2016** [sequelize/sequelize-auto#355]
sequelize-auto@0.4.29
mysql@2.15.0
mysql -u root -p join in is ok
but sequelize-auto -o "./models" -d test1 -h 127.0.0.1 -u root -p 3306 -x 123456 -e mysql is error:
{ SequelizeAccessDeniedError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)
at Handshake._callback (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:83:20)
at Handshake.Sequence.end (/usr/local/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
at Handshake.ErrorPacket (/usr/local/lib/node_modules/mysql/lib/protocol/sequences/Handshake.js:132:8)
at Protocol._parsePacket (/usr/local/lib/node_modules/mysql/lib/protocol/Protocol.js:279:23)
at Parser.write (/usr/local/lib/node_modules/mysql/lib/protocol/Parser.js:76:12)
at Protocol.write (/usr/local/lib/node_modules/mysql/lib/protocol/Protocol.js:39:16)
at Socket. (/usr/local/lib/node_modules/mysql/lib/Connection.js:103:28)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at addChunk (_stream_readable.js:263:12)
at readableAddChunk (_stream_readable.js:250:11)
at Socket.Readable.push (_stream_readable.js:208:10)
at TCP.onread (net.js:601:20)
name: 'SequelizeAccessDeniedError',
message: 'ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)...
please help~

**Comment by steveschmitt** [comment]
Any luck getting past this?  Please try with `sequelize-auto@0.5.0`  and let me know if it is still an issue.

**Comment by steveschmitt** [comment]
I think this was a problem with older `sequelize-auto` because it used an older version of `sequelize`.  Working in current version.
