### ISSUE TITLE
cannot connect with user credentials

### ISSUE THREAD

**Issue by Nosthertus** [sequelize/sequelize-auto#36]
just used this components with the credentials i use normally, but returns an error

```sh
sequelize-auto -h 127.0.0.1 -d fettle -u root -x 1324 -e mysql -o "./modelss"

{ [SequelizeAccessDeniedError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)]
  name: 'SequelizeAccessDeniedError',
  message: 'ER_ACCESS_DENIED_ERROR: Access denied for user \'root\'@\'localhost\' (using password: YES)',
  parent:
   { [Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)]
     code: 'ER_ACCESS_DENIED_ERROR',
     errno: 1045,
     sqlState: '28000',
     fatal: true },
  original:
   { [Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)]
     code: 'ER_ACCESS_DENIED_ERROR',
     errno: 1045,
     sqlState: '28000',
     fatal: true } }
```

**Comment by shangcloud** [comment]
mysql error
sequelize-auto -o "/Users/models" -d user -h localhost -u root -p 3306 -x 123456 -e mysql

{ [SequelizeAccessDeniedError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)]
  name: 'SequelizeAccessDeniedError',
  message: 'ER_ACCESS_DENIED_ERROR: Access denied for user \'root\'@\'localhost\' (using password: YES)',
  parent: 
   { [Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)]
     code: 'ER_ACCESS_DENIED_ERROR',
     errno: 1045,
     sqlState: '28000',
     fatal: true },
  original: 
   { [Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)]
     code: 'ER_ACCESS_DENIED_ERROR',
     errno: 1045,
     sqlState: '28000',
     fatal: true } }

**Comment by shangcloud** [comment]
hope resolve it！thank you

**Comment by shangcloud** [comment]
var auto = new sequelizeAuto(argv.d + '', argv.u + '', argv.x || null, configFile);

typeof argv.x is number! but it need to be a string. so it will tell me password is wrong!

**Comment by durango** [comment]
Let me know if the latest version has resolved your issue @Nosthertus and thanks @shangcloud  :) I'll close this ticket after a while/I get confirmation (just published the latest patch to npm).

**Comment by Nosthertus** [comment]
@durango looks like it works now, thanks for the fix patch

**Comment by Nosthertus** [comment]
i'll let you close this issue for the reason that seems like someone else has this kind of problem

**Comment by malick-it** [comment]
Hello .

Having the same issue ...

root@frontend:/var/apps/v1# sequelize-auto -o "./models" -d sequelize_auto_test -h 127.0.0.1 -u root -x mySecret -e mysql
{ SequelizeAccessDeniedError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)
    at Handshake._callback (/root/.nvm/versions/node/v6.10.2/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:
83:20)
    at Handshake.Sequence.end (/root/.nvm/versions/node/v6.10.2/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at Handshake.ErrorPacket (/root/.nvm/versions/node/v6.10.2/lib/node_modules/mysql/lib/protocol/sequences/Handshake.js:105:8)
    at Protocol._parsePacket (/root/.nvm/versions/node/v6.10.2/lib/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/root/.nvm/versions/node/v6.10.2/lib/node_modules/mysql/lib/protocol/Parser.js:75:12)

**Comment by mhyassin** [comment]
Here too

**Comment by tvankith** [comment]
same issue happen for me in latest version

**Comment by igorvolnyi** [comment]
It's sort of weird and funny. Access denied with -x option. And **WORKS WITHOUT IT**!!!

**Comment by samyulam2016** [comment]
i have save problem
sequelize-auto@0.4.29
mysql@2.15.0
mysql -u root -p join in is ok
but sequelize-auto -o "./models" -d test1 -h 127.0.0.1 -u root -p 3306 -x 123456 -e mysql is error:
{ SequelizeAccessDeniedError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: YES)
    at Handshake._callback (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/dialects/mysql/connection-manager.js:83:20)
    at Handshake.Sequence.end (/usr/local/lib/node_modules/mysql/lib/protocol/sequences/Sequence.js:88:24)
    at Handshake.ErrorPacket (/usr/local/lib/node_modules/mysql/lib/protocol/sequences/Handshake.js:132:8)
    at Protocol._parsePacket (/usr/local/lib/node_modules/mysql/lib/protocol/Protocol.js:279:23)
    at Parser.write (/usr/local/lib/node_modules/mysql/lib/protocol/Parser.js:76:12)
    at Protocol.write (/usr/local/lib/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/usr/local/lib/node_modules/mysql/lib/Connection.js:103:28)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:601:20)
  name: 'SequelizeAccessDeniedError',
  message: 'ER_ACCESS_DENIED_ERROR: Access denied for user \'root\'@\'localhost\' (using password: YES)...
please help~

**Comment by ubosquet** [comment]
guys what was the solution again, because I am getting the same issue .

**Comment by javeedrahman** [comment]
@ubosquet 
Have you sorted out these issues? I am getting some issues.

**Comment by A-Kasaaian** [comment]
I had the same issue but I added double quotations to password and it worked.
`-x "123"`

**Comment by jstafford74** [comment]
I had this issue and used the following syntax to solve my problem, running on node.js sequelize 5.12.3/sequelize auto .4.29 & mysql 2.17.1 

sequelize-auto -o "./models" -h localhost -d databasename -u root -p 3306 -x 'my_password'

**Comment by timolecoola** [comment]
Awesome @jstafford74! The ace in the hole is use apostrophe, I was using quotes...
Thanks man!
