### ISSUE TITLE
Windows basedir error

### ISSUE THREAD

**Issue by guru-apr21** [sequelize/sequelize-auto#473]
![guru-apr21@LAPTOP-24P4SG3M_ _mnt_c_users_akash_node-applications_sql_node_modules_ bin 21-12-2020 21_49_37](https://user-images.githubusercontent.com/69163711/102797986-76324380-43d6-11eb-94b0-13b62911c826.png)
```console
C:\Users\akash\node-applications\sql\node_modules\.bin\sequelize-auto:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
←[90m    at wrapSafe (internal/modules/cjs/loader.js:1054:16)←[39m
←[90m    at Module._compile (internal/modules/cjs/loader.js:1102:27)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:986:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:879:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)←[39m
←[90m    at internal/main/run_main_module.js:17:47←[39m
```
I get this error when I try to execute this command.
```console
 node sequelize-auto -o "./models" -d test -h localhost -u root -p 3306 -x pass -e mysql
```

**Comment by guru-apr21** [comment]
Used the root bin instead of sequelize auto bin. Issue resolved

**Comment by mbanna-smart** [comment]
@guru-apr21 Can you please give more more details how you solve the problem?

**Comment by guru-apr21** [comment]
Replace node with npx. npx is a package runner tool which comes with npm version greater than 6.

**Comment by steveschmitt** [comment]
@mbanna-smart as Guru said, your command should be 
```
 npx sequelize-auto -o "./models" -d test -h localhost -u root -p 3306 -x pass -e mysql
```
