### ISSUE TITLE
error _.contains is not a function in Postgres

### ISSUE THREAD

**Issue by deka6pb** [sequelize/sequelize-auto#57]
Hello I have Postgres db.
When I write command 
`sequelize-auto -o "./models" -d sequelize_auto_test -h localhost -u my_username -p 5432 -x my_password -e postgres`
with my params I have this error in console:
```
Unhandled rejection TypeError: _.contains is not a function
    at Object.exports.postgres.isSerialKey (/usr/local/lib/node_modules/sequelize-auto/lib/dialects/index.js:130:14)
    at /usr/local/lib/node_modules/sequelize-auto/lib/index.js:124:110
    at arrayEach (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/node_modules/lodash/lodash.js:473:11)
    at Function.forEach (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/node_modules/lodash/lodash.js:7607:11)
    at /usr/local/lib/node_modules/sequelize-auto/lib/index.js:123:11
    at arrayEach (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/node_modules/lodash/lodash.js:473:11)
    at Function.forEach (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/node_modules/lodash/lodash.js:7607:11)
    at /usr/local/lib/node_modules/sequelize-auto/lib/index.js:103:9
    at /usr/local/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/usr/local/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/usr/local/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:209:22)
    at generateText (/usr/local/lib/node_modules/sequelize-auto/lib/index.js:91:11)
    at /usr/local/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:52:16
    at done (/usr/local/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:246:17)
    at /usr/local/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:44:16
    at /usr/local/lib/node_modules/sequelize-auto/lib/index.js:83:7
```

**Comment by santiag00** [comment]
I'm getting the exact same error using Postgres 9.4.5

**Comment by durango** [comment]
This should be fixed in the latest
