### ISSUE TITLE
mssql -Unhandled rejection TypeError: undefined is not a function at Object.module.exports.removeTicks

### ISSUE THREAD

**Issue by ieow** [sequelize/sequelize-auto#59]
├── sequelize@3.19.1
├── sequelize-auto@0.2.13
├── tedious@1.13.2
└── uglify-js@2.4.24

I am hitting this issue with the environment above when tried to retrieve mssql model

Executing (default): SELECT TABLE_NAME, TABLE_SCHEMA FROM INFORMATION_SCHEMA.TABLES;
Unhandled rejection TypeError: undefined is not a function
    at Object.module.exports.removeTicks (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/utils.js:376:14)
    at Object.module.exports.addTicks (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/utils.js:372:29)
    at Object.exports.mssql.getForeignKeysQuery (/usr/local/lib/node_modules/sequelize-auto/lib/dialects/index.js:155:54)
    at mapForeignKeys (/usr/local/lib/node_modules/sequelize-auto/lib/index.js:44:23)
    at /usr/local/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/usr/local/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/usr/local/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:209:22)
    at /usr/local/lib/node_modules/sequelize-auto/lib/index.js:38:11
    at tryCatcher (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:491:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:548:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:593:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/node_modules/bluebird/js/release/promise.js:676:18)
    at Async._drainQueue (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/node_modules/bluebird/js/release/async.js:125:16)
    at Async._drainQueues (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/node_modules/bluebird/js/release/async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/node_modules/bluebird/js/release/async.js:16:14)

Anyone having similar issue?

**Comment by ihorskyi** [comment]
@ieow could you please provide SQL for that table to reproduce issue?

**Comment by mike-munchdev** [comment]
I'm having a similar issue using npm on OSX El Capitan connecting to SQL Express 2012. 

Executing (default): SELECT TABLE_NAME, TABLE_SCHEMA FROM INFORMATION_SCHEMA.TABLES;
Unhandled rejection TypeError: s.replace is not a function
    at Object.module.exports.removeTicks (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/utils.js:376:14)
    at Object.module.exports.addTicks (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/utils.js:372:29)
    at Object.exports.mssql.getForeignKeysQuery (/usr/local/lib/node_modules/sequelize-auto/lib/dialects/index.js:155:54)
    at mapForeignKeys (/usr/local/lib/node_modules/sequelize-auto/lib/index.js:44:23)
    at /usr/local/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/usr/local/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/usr/local/lib/node_modules/sequelize-auto/node_modules/async/lib/async.js:209:22)
    at /usr/local/lib/node_modules/sequelize-auto/lib/index.js:38:11
    at tryCatcher (/usr/local/lib/node_modules/sequelize-auto/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/sequelize-auto/node_modules/bluebird/js/release/promise.js:491:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/sequelize-auto/node_modules/bluebird/js/release/promise.js:548:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/sequelize-auto/node_modules/bluebird/js/release/promise.js:593:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/sequelize-auto/node_modules/bluebird/js/release/promise.js:676:18)
    at Async._drainQueue (/usr/local/lib/node_modules/sequelize-auto/node_modules/bluebird/js/release/async.js:125:16)
    at Async._drainQueues (/usr/local/lib/node_modules/sequelize-auto/node_modules/bluebird/js/release/async.js:135:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/sequelize-auto/node_modules/bluebird/js/release/async.js:16:14)

**Comment by ebenmoha** [comment]
@mike-munchdev I had the same error, this pull request fixed the problem : https://github.com/sequelize/sequelize-auto/pull/60

**Comment by durango** [comment]
Should be fixed with #60 being merged
