### ISSUE TITLE
unknown bug on sequelize auto

### ISSUE THREAD

**Issue by noname29** [sequelize/sequelize-auto#664]
When I run this, this is the error I get. I am on ubuntu.

my command: 
`sequelize-auto -o "./models" -d bookcollection -h localhost -u root -p 3306 -x password -e mysql
`
Versions:
sequelize-auto@0.8.8
sequelize@6.37.2
mysql2@3.9.4

```
/usr/local/lib/node_modules/mysql2/node_modules/lru-cache/dist/cjs/index.js:51
    heap;
        ^

SyntaxError: Unexpected token ;
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/mysql2/node_modules/lru-cache/dist/cjs/index-cjs.js:5:36)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

```

**Comment by WikiRik** [comment]
What Node version are you using?
