### ISSUE TITLE
Mention something about installing the dialect module globally in the docs ?

### ISSUE THREAD

**Issue by CGavrila** [sequelize/sequelize-auto#9]
I tried using the tool as explained in the README file.

I installed the sequelize-auto module globally and then kept hitting:

```
You need to install mysql package manually

/home/cristi/.nvm/v0.10.33/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/dialects/mysql/connector-manager.js:306
    var connection = mysql.createConnection(connectionConfig);
                           ^
TypeError: Cannot call method 'createConnection' of undefined
    at module.exports.connect (/home/cristi/.nvm/v0.10.33/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/dialects/mysql/connector-manager.js:306:28)
    at Object.pool.Pooling.Pool.create (/home/cristi/.nvm/v0.10.33/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/dialects/mysql/connector-manager.js:131:19)
    at createResource (/home/cristi/.nvm/v0.10.33/lib/node_modules/sequelize-auto/node_modules/sequelize/node_modules/generic-pool/lib/generic-pool.js:258:13)
    at dispense (/home/cristi/.nvm/v0.10.33/lib/node_modules/sequelize-auto/node_modules/sequelize/node_modules/generic-pool/lib/generic-pool.js:250:9)
    at Object.me.acquire (/home/cristi/.nvm/v0.10.33/lib/node_modules/sequelize-auto/node_modules/sequelize/node_modules/generic-pool/lib/generic-pool.js:316:5)
    at null.fct (/home/cristi/.nvm/v0.10.33/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/dialects/mysql/connector-manager.js:241:19)
    at null.<anonymous> (/home/cristi/.nvm/v0.10.33/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/emitters/custom-event-emitter.js:24:18)
    at processImmediate [as _immediateCallback] (timers.js:345:15)
```

The issue was that I did not have mysql installed globally (`npm install -g mysql`). Maybe you could update the README file with a small note on this? Otherwise, at least someone having the same issue might have the fix here.

Not much of a big deal, so feel free to ignore.

**Comment by lesmo** [comment]
It probably has to do with those packages being under ```devDependencies```. Maybe if they're moved to ```dependencies``` this won't happen?

**Comment by payne8** [comment]
I can verify that simply having mysql install in the local npm project is not sufficient. I could only get it to run if mysql was installed globally.

**Comment by HannahWatwood** [comment]
I agree with this, I got the same error. Glad I checked the repo before giving up.

**Comment by durango** [comment]
I know it's a bit late, sorry for the troubles hopefully this [the commit] will help others in the future. Thanks :+1:

**Comment by CGavrila** [comment]
It's an open source project, nobody should complain about stuff not working as long as they're not willing to put in the time and effort to fix it. So thank you @durango!
