### ISSUE TITLE
terraformer-wkt-parser Module not found

### ISSUE THREAD

**Issue by captainjackrana** [sequelize/sequelize-auto#98]
Running the following command on my local mysql db schema (mydb) gives the following error - 

> module.js:442
    throw err;
    ^

Error: Cannot find module 'terraformer-wkt-parser'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/data-types.js:6:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/sequelize-auto/node_modules/sequelize/lib/utils.js:3:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)

Here is the exact command that is being executed
sequelize-auto -o "./nodesrc/models" -d mydb -h localhost -u root -p 3306 -x -e mysql

**Comment by captainjackrana** [comment]
Run npm update -g terraformer-wkt-parser

**Comment by durango** [comment]
This looks like an issue with `sequelize` as opposed to `sequelize-auto` closing
